---
title: "SpotifyR_2023"
output:
  pdf_document: default
  html_notebook: default
---


```{r}
spot0 = read.csv("StreamingHistory20230.csv")
spot1 = read.csv("StreamingHistory20231.csv")
spot2 = read.csv("StreamingHistory20232.csv")
spot3 = read.csv("StreamingHistory20233.csv")
```

```{r}
streamHistory0 <- spot0  
  as_tibble()  
  mutate_at("endTime", ymd_hm)  
  mutate(endTime = endTime - hours(6))  
  mutate(date = floor_date(endTime, "day"), as_date, seconds = msPlayed / 1000, minutes = seconds / 60)

streamHistory1 <- spot1 
  as_tibble()  
  mutate_at("endTime", ymd_hm)  
  mutate(endTime = endTime - hours(6))  
  mutate(date = floor_date(endTime, "day"), as_date, seconds = msPlayed / 1000, minutes = seconds / 60)

streamHistory2 <- spot2  
  as_tibble()  
  mutate_at("endTime", ymd_hm)  
  mutate(endTime = endTime - hours(6))  
  mutate(date = floor_date(endTime, "day"), as_date, seconds = msPlayed / 1000, minutes = seconds / 60)

streamHistory3 <- spot3  
  as_tibble()  
  mutate_at("endTime", ymd_hm) 
  mutate(endTime = endTime - hours(6))  
  mutate(date = floor_date(endTime, "day"), as_date, seconds = msPlayed / 1000, minutes = seconds / 60)
```

```{r}
mySpotify <- vctrs::vec_c(streamHistory0, streamHistory1, streamHistory2, streamHistory3)
```


```{r}
minutesTMostListened <- mySpotify 
  filter(date >= "2023-01-01") 
  group_by(trackName)  
  summarize(minutesListened = sum(minutes))  
  filter(minutesListened >= 180) 
  ggplot(aes(x = reorder(trackName, minutesListened), y = minutesListened)) + 
  geom_col(aes(fill = minutesListened)) +
  scale_fill_gradient(low = "#1db954", high = "#1db954") + 
  labs(x= "Song", y= "Minutes") + 
  ggtitle("Most listened songs") +
  theme(axis.text.x = element_text(angle = 90))
minutesTMostListened + coord_flip()
```

```{r}
hoursDay <- mySpotify  
  filter(date >= "2023-01-01")  
  group_by(date, hour = hour(endTime), weekday = wday(date, label = TRUE)) 
  summarize(minutesListened = sum(minutes))
hoursDay  
  ggplot(aes(x = hour, y = minutesListened, group = date)) + 
  geom_col(fill = "#1db954") + 
  labs(x= "Time of the day", y= "Minutes") + 
  ggtitle("Activity from 0 to 24 hours")
```

```{r}
weekDay <- hoursDay  
  group_by(weekday, hour)  
  summarize(minutes = sum(minutesListened))  
  ggplot(aes(x = hour, y = minutes, color = weekday)) + 
  geom_line() + 
  labs(x= "Time of the day", y= "Minutes") + 
  ggtitle("Weekly activity from 0 to 24 hours") 
weekDay
```

```{r}
minutesMostListened <- mySpotify 
  filter(date >= "2020-01-01")  
  group_by(artistName)  
  summarize(minutesListened = sum(minutes))  
  filter(minutesListened >= 180) 
  ggplot(aes(x = reorder(artistName, minutesListened), y = minutesListened)) + 
  geom_col(aes(fill = minutesListened)) + 
  scale_fill_gradient(low = "#1db954", high = "#1db954") + 
  labs(x= "Artist", y= "Minutes") + 
  ggtitle("Playback activity per artist") +
  theme(axis.text.x = element_text(angle = 90))
minutesMostListened + coord_flip()
```

```{r}
minutesMostListened <- mySpotify 
  filter(date >= "2023-01-01") 
  group_by(artistName) 
  summarize(minutesListened = sum(minutes)) 
  filter(minutesListened >= 1200) 
  ggplot(aes(x = artistName, y = minutesListened)) +
  geom_col(aes(fill = minutesListened)) +
  scale_fill_gradient(low = "yellow", high = "red") +
  labs(x = "Artist", y = "Minutes of music playback") +
  ggtitle("What were the most listened artists on my Spotify?", ">20 hours listened") +
  theme(axis.text.x = element_text(angle = 90))
minutesMostListened
```


```{r}
streamingHours <- mySpotify  
  filter(date >= "2020-01-01")  
  group_by(date)  
  group_by(date = floor_date(date, "week")) 
  summarize(hours = sum(minutes) / 60)  
  arrange(date)  
  ggplot(aes(x = date, y = hours)) + 
  geom_col(aes(fill = hours)) + 
  scale_fill_gradient(low = "#1db954", high = "#1db954") + 
  labs(x= "Date", y= "Hours") + 
  ggtitle("Playback activity per week")
streamingHours
```


```{r}
hoursArtist <- mySpotify  
  group_by(artistName, date = floor_date(date, "month"))  
  summarize(hours = sum(minutes) / 60)  
  ggplot(aes(x = date, y = hours, group = artistName, color = artistName)) + 
  labs(x= "Date", y= "Hours") + 
  ggtitle("Playback activity per artist") +
  geom_line() + 
  gghighlight(artistName == "Taylor Swift" || artistName == "SZA" || artistName == "Noah Kahan"|| artistName == "Tyler, The Creator") 
hoursArtist
```


```{r}
timeDay <- mySpotify 
  filter(date >= "2023-01-01") 
  group_by(date, hour = hour(endTime)) 
  summarize(minutesListened = sum(minutes)) 
  ggplot(aes(x = hour, y = date, fill = minutesListened)) +
  geom_tile() +
  labs(x = "Time of the day", y = "Date") +
  ggtitle("When has there been more playback activity on my Spotify?", "Activity by date and time of day") +
  scale_fill_gradient(low = "yellow", high = "red")
timeDay
```

```{r}
hoursDay 
  group_by(weekday, hour) 
  summarize(minutes = sum(minutesListened)) 
  ggplot(aes(x = hour, weekday, fill = minutes)) +
  geom_tile() +
  scale_fill_gradient(low = "yellow", high = "red") +
  labs(x = "Time of the day", y = "Weekday") +
  ggtitle("What weekeday and time of day I've listened to the most music on Spotify?", "Weekly activity from 0 to 24 hours")
```

```{r}
sum(mySpotify$minutes)

```

```{r}
sum(mySpotify[which(mySpotify$artistName=="Taylor Swift"), 7])

```


```{r}
sum(mySpotify[which(mySpotify$artistName=="SZA"), 7])

```

```{r}
sum(mySpotify[which(mySpotify$artistName=="Noah Kahan"), 7])

```

```{r}
sum(mySpotify[which(mySpotify$artistName=="Tyler, The Creator"), 7])

```

```{r}
sum(mySpotify[which(mySpotify$artistName=="Hozier"), 7])

```

```{r}
sum(mySpotify[which(mySpotify$artistName=="Olivia Rodrigo"), 7])

```

```{r}
sum(mySpotify[which(mySpotify$trackName=="Bags"), 7])
sum(mySpotify[which(mySpotify$trackName=="Bags"), 7])/4.3

```

```{r}
sum(mySpotify[which(mySpotify$trackName=="Satellite"), 7])
sum(mySpotify[which(mySpotify$trackName=="Satellite"), 7])/3.63

```

```{r}
sum(mySpotify[which(mySpotify$trackName=="You’re Gonna Go Far"), 7])
sum(mySpotify[which(mySpotify$trackName=="You’re Gonna Go Far"), 7])/4.76
```

```{r}
sum(mySpotify[which(mySpotify$trackName=="SWEET / I THOUGHT YOU WANTED TO DANCE (feat. Brent Faiyaz & Fana Hues)"), 7])
sum(mySpotify[which(mySpotify$trackName=="SWEET / I THOUGHT YOU WANTED TO DANCE (feat. Brent Faiyaz & Fana Hues)"), 7])/9.8
```

```{r}
sum(mySpotify[which(mySpotify$trackName=="Too Many Nights (feat. Don Toliver & with Future)"), 7])
sum(mySpotify[which(mySpotify$trackName=="Too Many Nights (feat. Don Toliver & with Future)"), 7])/3.32
```

```{r}
sum(mySpotify[which(mySpotify$trackName=="DOGTOOTH"), 7])
sum(mySpotify[which(mySpotify$trackName=="DOGTOOTH"), 7])/2.68

```


```{r}
sum(mySpotify[which(mySpotify$trackName=="Baby Girl"), 7])
sum(mySpotify[which(mySpotify$trackName=="Baby Girl"), 7])/1.85
```

```{r}
sum(mySpotify[which(mySpotify$trackName=="Boy's a liar Pt. 2"), 7])
sum(mySpotify[which(mySpotify$trackName=="Boy's a liar Pt. 2"), 7])/2.18
```






